
* Trainable-Object

This library provides an abstract class and CLOS APIs for the trainable funcallable instances.

The library is almost blank; It has no actual implementations in it.
Its sole purpose is to provide the interface for a machine learning model.

** API

: Class TRAINABLE-OBJECT (SERIALIZABLE-OBJECT)
: Generic Function (train    model input output &key verbose val-input val-output test-input test-output &allow-other-keys)
: Generic Function (evaluate model input output &key verbose &allow-other-keys)
: Generic Function (predict  model input        &key verbose &allow-other-keys)

** Dependencies
This library is at least tested on implementation listed below:

+ SBCL 1.4.12 on X86-64 Linux 4.4.0-142-generic (author's environment)

Also, it depends on the following libraries:

+ trivia by *Masataro Asai* :
    NON-optimized pattern matcher compatible with OPTIMA, with extensible optimizer interface and clean codebase
+ alexandria by *Nikodemus Siivola <nikodemus@sb-studio.net>, and others.* :
    Alexandria is a collection of portable public domain utilities.
+ iterate by ** :
    Jonathan Amsterdam's iterator/gatherer/accumulator facility
+ closer-mop by *Pascal Costanza* :
    Closer to MOP is a compatibility layer that rectifies many of the absent or incorrect CLOS MOP features across a broad range of Common Lisp implementations.

** Installation

** Author, License, Copyright

Licensed under LGPL v3.

Copyright (c) 2019 Masataro Asai (guicho2.71828@gmail.com)
Copyright (c) 2019 IBM Corporation
